apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  labels:
    {{- include "commonLabels" . | indent 4 }}
data:
  backends: |
{{ join "\n" .Values.backends | indent 4 }}

