apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "commonLabels" . | indent 4 }}
  annotations:
{{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "commonLabels" . | indent 4 }}
    app: haproxy
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote}}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.containerPorts }}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  {{- end }}
